#!/usr/bin/env node

const path = require('path')

const fsExtra = require('fs-extra')
const minimist = require('minimist')

const argv = minimist(process.argv.slice(2));

const [commandIn, ...args] = argv._
const commandMod = commandIn.toLowerCase().replace(/sync$/, '').replace(/[^a-z]/g, '') + 'sync'
const [command, ...others] = Object.keys(fsExtra).filter(fsCmd => fsCmd.toLowerCase() === commandMod)
delete argv._
args.push(argv)

try {
  const result = fsExtra[command](...args)
  if (result !== undefined) {
    console.log(JSON.stringify(result, null, 2))
  }
} catch (err) {
  console.error(err.message)
}
